sources:
  - name: GeoDB
    handler:
        openapi:
          source: https://wirefreethought.github.io/geodb-cities-api-docs/swagger.json
          baseUrl: http://geodb-free-service.wirefreethought.com/v1/
  - name: OpenBrewery
    handler:
      jsonSchema:
        baseUrl: https://api.openbrewerydb.org
        operations:
          - type: Query
            field: breweries
            path: breweries
            method: GET
            requestSample: ./src/openbrewery/breweriesInputSample.json
            responseSample: ./src/openbrewery/breweriesSample.json

additionalTypeDefs: |
      extend type PopulatedPlaceSummary {
          breweries: [_query_breweries_items]
      }

additionalResolvers:
  - targetTypeName: PopulatedPlaceSummary
    targetFieldName: breweries
    requiredSelectionSet: |
      { 
        name 
      }
    sourceName: OpenBrewery
    sourceTypeName: Query
    sourceFieldName: breweries
    sourceArgs:
      "input.by_city": '{root.name}'

documents: 
  - ./example-query.graphql

serve:
  port: 4000

